import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';

/**
 * One flat config for the whole workspace.
 *
 * Deliberately NOT type-aware: type-aware linting would duplicate what
 * `pnpm typecheck` already does across 10 projects, for several times the
 * runtime. This layer is here to catch what the compiler cannot — unused code,
 * accidental globals, and React hook dependency mistakes (the class of bug that
 * left a finished workout on screen forever).
 */
export default tseslint.config(
  {
    ignores: [
      '**/dist/**',
      '**/.next/**',
      '**/node_modules/**',
      '**/coverage/**',
      '**/playwright-report/**',
      '**/test-results/**',
      'packages/db/generated/**',
      // Generated by `next build`; not ours to satisfy.
      'apps/web/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      globals: { ...globals.node },
    },
    rules: {
      // A leading underscore is the established way to say "deliberately unused"
      // — a caught error you do not inspect, a positional parameter you must
      // accept to reach the next one.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrors: 'all',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      // Empty catch blocks are a real pattern here (best-effort paths that must
      // not break the request), but they have to say so in a comment.
      'no-empty': ['error', { allowEmptyCatch: false }],
      // Logging goes through Nest's logger or the structured request log, so a
      // stray console.log is either debug residue or a place a secret can leak.
      // The two deliberate structured-log writes carry a disable directive.
      'no-console': ['error', { allow: ['warn', 'error'] }],
    },
  },

  // Browser code.
  {
    files: ['apps/web/**/*.{ts,tsx}'],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
    plugins: { 'react-hooks': reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,
      // v7 of this plugin also ships the React Compiler's rules. They police a
      // style this codebase has not adopted — reading localStorage or a URL
      // param in a mount effect and calling setState, or reading the clock
      // during render — all of which are correct, deliberate, and verified
      // working here. Enforcing them would mean rewriting shipped, tested
      // behaviour to satisfy a compiler Atlas does not run. The rules that
      // catch actual bugs (rules-of-hooks, exhaustive-deps) stay on.
      'react-hooks/set-state-in-effect': 'off',
      'react-hooks/purity': 'off',
      'react-hooks/immutability': 'off',
      'react-hooks/globals': 'off',
    },
  },

  // The service worker runs in its own global scope.
  {
    files: ['apps/web/public/**/*.js'],
    languageOptions: {
      globals: { ...globals.serviceworker, ...globals.browser },
    },
  },

  // Tests may lean on non-null assertions to keep fixtures readable, and print
  // freely. `any` stays banned — the existing fakes disable it per line, which
  // keeps each cast a visible decision instead of a blanket exemption.
  {
    files: ['**/test/**/*.{ts,tsx}', '**/e2e/**/*.ts', '**/*.test.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-non-null-assertion': 'off',
      'no-console': 'off',
    },
  },
);
