import type { Equipment, ExerciseKind, MuscleGroup, MuscleTarget } from '@atlas/shared';

/**
 * The shared catalog, seeded once with `userId = null` so every account gets it.
 *
 * It used to be forty-eight movements, chosen to keep the picker scannable. That
 * was the wrong trade: a catalog you cannot find your exercise in is not a
 * scannable catalog, it is a dead end with an "add exercise" button, and the
 * thing that made it obvious was hip abduction — a machine in every commercial
 * gym, filed under "legs" along with squats, and therefore unfindable.
 *
 * So it is now broad, and the picker does the narrowing instead: search by name,
 * filter by the specific muscle, filter by what the equipment is. Breadth costs
 * nothing once the list is filterable, and the entries carry enough structure
 * for the filters to be honest.
 *
 * ENTRIES ARE KEYED BY TARGET, not listed flat, so the muscle a movement trains
 * is stated once for a whole block and the coarse group is DERIVED from it.
 * Writing both by hand on four hundred rows guarantees a few disagree with each
 * other, and a "back" exercise filed under quads is worse than a missing one.
 */
export interface CatalogEntry {
  name: string;
  muscle: MuscleGroup;
  target: MuscleTarget;
  equipment: Equipment;
  kind: ExerciseKind;
}

/** Every specific muscle rolls up to exactly one coarse group. */
const GROUP_OF: Record<MuscleTarget, MuscleGroup> = {
  upper_chest: 'chest',
  mid_chest: 'chest',
  lower_chest: 'chest',
  lats: 'back',
  upper_back: 'back',
  traps: 'back',
  lower_back: 'back',
  rear_delts: 'shoulders',
  front_delts: 'shoulders',
  side_delts: 'shoulders',
  rotator_cuff: 'shoulders',
  biceps: 'arms',
  triceps: 'arms',
  forearms: 'arms',
  quads: 'legs',
  hamstrings: 'legs',
  glutes: 'legs',
  calves: 'legs',
  adductors: 'legs',
  abductors: 'legs',
  hip_flexors: 'legs',
  tibialis: 'legs',
  abs: 'core',
  obliques: 'core',
  lower_abs: 'core',
  neck: 'other',
  full_body: 'other',
  cardio: 'cardio',
  other: 'other',
};

/** `[name, equipment, kind?]` — kind defaults to weight_reps. */
type Row = [string, Equipment] | [string, Equipment, ExerciseKind];

const BY_TARGET: Partial<Record<MuscleTarget, Row[]>> = {
  // ── Chest ────────────────────────────────────────────────────────────────
  mid_chest: [
    ['Bench Press (Barbell)', 'barbell'],
    ['Bench Press (Dumbbell)', 'dumbbell'],
    ['Bench Press (Smith Machine)', 'smith'],
    ['Chest Press (Machine)', 'machine'],
    ['Chest Press (Plate-Loaded)', 'machine'],
    ['Chest Fly (Dumbbell)', 'dumbbell'],
    ['Chest Fly (Machine)', 'machine'],
    ['Cable Fly (Mid)', 'cable'],
    // Original name, kept so the existing row gets classified rather than orphaned.
    ['Chest Fly (Cable)', 'cable'],
    ['Cable Press (Standing)', 'cable'],
    ['Push Up', 'bodyweight', 'reps'],
    ['Push Up (Weighted)', 'plate'],
    ['Wide-Grip Push Up', 'bodyweight', 'reps'],
    ['Ring Push Up', 'suspension', 'reps'],
    ['Floor Press (Barbell)', 'barbell'],
    ['Floor Press (Dumbbell)', 'dumbbell'],
    ['Svend Press', 'plate'],
    ['Pec Deck', 'machine'],
    ['Landmine Press (Kneeling)', 'barbell'],
  ],
  upper_chest: [
    ['Incline Bench Press (Barbell)', 'barbell'],
    ['Incline Bench Press (Dumbbell)', 'dumbbell'],
    ['Incline Bench Press (Smith Machine)', 'smith'],
    ['Incline Chest Press (Machine)', 'machine'],
    ['Incline Fly (Dumbbell)', 'dumbbell'],
    ['Low-to-High Cable Fly', 'cable'],
    ['Incline Push Up', 'bodyweight', 'reps'],
    ['Landmine Press (Standing)', 'barbell'],
  ],
  lower_chest: [
    ['Decline Bench Press (Barbell)', 'barbell'],
    ['Decline Bench Press (Dumbbell)', 'dumbbell'],
    ['High-to-Low Cable Fly', 'cable'],
    ['Chest Dip', 'bodyweight', 'reps'],
    ['Chest Dip (Weighted)', 'plate'],
    ['Decline Push Up', 'bodyweight', 'reps'],
  ],

  // ── Back ─────────────────────────────────────────────────────────────────
  lats: [
    ['Pull Up', 'bodyweight', 'reps'],
    ['Pull Up (Weighted)', 'plate'],
    ['Chin Up', 'bodyweight', 'reps'],
    ['Neutral-Grip Pull Up', 'bodyweight', 'reps'],
    ['Assisted Pull Up (Machine)', 'machine'],
    ['Lat Pulldown (Cable)', 'cable'],
    ['Wide-Grip Lat Pulldown', 'cable'],
    ['Close-Grip Lat Pulldown', 'cable'],
    ['Reverse-Grip Lat Pulldown', 'cable'],
    ['Single-Arm Lat Pulldown', 'cable'],
    ['Straight-Arm Pulldown (Cable)', 'cable'],
    ['Pullover (Dumbbell)', 'dumbbell'],
    ['Pullover (Machine)', 'machine'],
    ['Barbell Row', 'barbell'],
    ['Pendlay Row', 'barbell'],
    ['Dumbbell Row', 'dumbbell'],
    ['Chest-Supported Row (Machine)', 'machine'],
    ['Seated Row (Cable)', 'cable'],
    ['Wide-Grip Seated Row', 'cable'],
    ['T-Bar Row', 'barbell'],
    ['Meadows Row', 'barbell'],
    ['Kroc Row', 'dumbbell'],
    ['Inverted Row', 'bodyweight', 'reps'],
    ['Ring Row', 'suspension', 'reps'],
  ],
  upper_back: [
    ['Chest-Supported Row (Dumbbell)', 'dumbbell'],
    ['Seal Row', 'barbell'],
    ['Face Pull (Cable)', 'cable'],
    ['Rope Row to Neck', 'cable'],
    ['Reverse Fly (Machine)', 'machine'],
    ['Band Pull-Apart', 'band', 'reps'],
    ['Scapular Pull Up', 'bodyweight', 'reps'],
    ['Prone Y-Raise', 'dumbbell'],
    ['Prone T-Raise', 'dumbbell'],
  ],
  traps: [
    ['Shrug (Barbell)', 'barbell'],
    ['Shrug (Dumbbell)', 'dumbbell'],
    ['Shrug (Smith Machine)', 'smith'],
    ['Shrug (Trap Bar)', 'trap_bar'],
    ['Shrug (Cable)', 'cable'],
    ['Farmer Carry', 'dumbbell', 'duration'],
    ['Upright Row (Barbell)', 'barbell'],
    ['Upright Row (Cable)', 'cable'],
    ['Power Shrug', 'barbell'],
  ],
  lower_back: [
    ['Deadlift (Barbell)', 'barbell'],
    ['Deadlift (Trap Bar)', 'trap_bar'],
    ['Sumo Deadlift', 'barbell'],
    ['Deficit Deadlift', 'barbell'],
    ['Rack Pull', 'barbell'],
    ['Back Extension', 'bodyweight', 'reps'],
    ['Back Extension (Weighted)', 'plate'],
    ['45-Degree Hyperextension', 'bodyweight', 'reps'],
    ['Good Morning (Barbell)', 'barbell'],
    ['Reverse Hyperextension', 'machine'],
    ['Jefferson Curl', 'dumbbell'],
    ['Superman Hold', 'bodyweight', 'duration'],
  ],

  // ── Shoulders ────────────────────────────────────────────────────────────
  front_delts: [
    ['Overhead Press (Barbell)', 'barbell'],
    ['Overhead Press (Dumbbell)', 'dumbbell'],
    ['Seated Shoulder Press (Dumbbell)', 'dumbbell'],
    ['Shoulder Press (Dumbbell)', 'dumbbell'],
    ['Shoulder Press (Machine)', 'machine'],
    ['Shoulder Press (Smith Machine)', 'smith'],
    ['Arnold Press', 'dumbbell'],
    ['Push Press', 'barbell'],
    ['Front Raise (Dumbbell)', 'dumbbell'],
    ['Front Raise (Cable)', 'cable'],
    ['Front Raise (Plate)', 'plate'],
    ['Z Press', 'barbell'],
    ['Pike Push Up', 'bodyweight', 'reps'],
    ['Handstand Push Up', 'bodyweight', 'reps'],
  ],
  side_delts: [
    ['Lateral Raise (Dumbbell)', 'dumbbell'],
    ['Lateral Raise (Cable)', 'cable'],
    ['Lateral Raise (Machine)', 'machine'],
    ['Leaning Lateral Raise', 'dumbbell'],
    ['Lu Raise', 'dumbbell'],
    ['Behind-the-Back Cable Raise', 'cable'],
    ['Band Lateral Raise', 'band', 'reps'],
    ['Egyptian Lateral Raise', 'cable'],
  ],
  rear_delts: [
    ['Rear Delt Fly (Dumbbell)', 'dumbbell'],
    ['Rear Delt Fly (Cable)', 'cable'],
    ['Rear Delt Fly (Machine)', 'machine'],
    ['Bent-Over Reverse Fly', 'dumbbell'],
    ['Face Pull (Rope)', 'cable'],
    ['Rear Delt Row', 'barbell'],
  ],
  rotator_cuff: [
    ['External Rotation (Cable)', 'cable'],
    ['External Rotation (Band)', 'band', 'reps'],
    ['Internal Rotation (Cable)', 'cable'],
    ['Cuban Press', 'dumbbell'],
    ['Bottoms-Up Press (Kettlebell)', 'kettlebell'],
  ],

  // ── Arms ─────────────────────────────────────────────────────────────────
  biceps: [
    ['Bicep Curl (Dumbbell)', 'dumbbell'],
    ['Bicep Curl (Barbell)', 'barbell'],
    ['Bicep Curl (EZ-Bar)', 'ez_bar'],
    ['Cable Curl', 'cable'],
    ['Hammer Curl (Dumbbell)', 'dumbbell'],
    ['Hammer Curl (Cable)', 'cable'],
    ['Preacher Curl (EZ-Bar)', 'ez_bar'],
    ['Preacher Curl (Machine)', 'machine'],
    ['Incline Curl (Dumbbell)', 'dumbbell'],
    ['Concentration Curl', 'dumbbell'],
    ['Spider Curl', 'ez_bar'],
    ['Bayesian Curl (Cable)', 'cable'],
    ['Drag Curl', 'barbell'],
    ['21s Curl', 'barbell'],
    ['Zottman Curl', 'dumbbell'],
    ['Chin Up (Weighted)', 'plate'],
  ],
  triceps: [
    ['Tricep Pushdown (Cable)', 'cable'],
    ['Rope Pushdown', 'cable'],
    ['Straight-Bar Pushdown', 'cable'],
    ['Overhead Tricep Extension (Dumbbell)', 'dumbbell'],
    ['Overhead Tricep Extension (Cable)', 'cable'],
    ['Overhead Tricep Extension (EZ-Bar)', 'ez_bar'],
    ['Skull Crusher (Barbell)', 'barbell'],
    ['Skull Crusher (EZ-Bar)', 'ez_bar'],
    ['Skull Crusher (Dumbbell)', 'dumbbell'],
    ['Close-Grip Bench Press (Barbell)', 'barbell'],
    ['JM Press', 'barbell'],
    ['Tricep Dip', 'bodyweight', 'reps'],
    ['Dip', 'bodyweight', 'reps'],
    ['Bench Dip', 'bodyweight', 'reps'],
    ['Tricep Kickback (Dumbbell)', 'dumbbell'],
    ['Tricep Kickback (Cable)', 'cable'],
    ['Tricep Extension (Machine)', 'machine'],
    ['Diamond Push Up', 'bodyweight', 'reps'],
    ['Tate Press', 'dumbbell'],
  ],
  forearms: [
    ['Wrist Curl (Barbell)', 'barbell'],
    ['Wrist Curl (Dumbbell)', 'dumbbell'],
    ['Reverse Wrist Curl', 'dumbbell'],
    ['Reverse Curl (EZ-Bar)', 'ez_bar'],
    ['Reverse Curl (Cable)', 'cable'],
    ['Wrist Roller', 'other'],
    ['Dead Hang', 'bodyweight', 'duration'],
    ['Plate Pinch Hold', 'plate', 'duration'],
    ['Farmer Carry (Heavy)', 'dumbbell', 'duration'],
  ],

  // ── Legs ─────────────────────────────────────────────────────────────────
  quads: [
    ['Squat (Barbell)', 'barbell'],
    ['Front Squat (Barbell)', 'barbell'],
    ['High-Bar Squat', 'barbell'],
    ['Low-Bar Squat', 'barbell'],
    ['Box Squat', 'barbell'],
    ['Pause Squat', 'barbell'],
    ['Squat (Smith Machine)', 'smith'],
    ['Hack Squat (Machine)', 'machine'],
    ['Pendulum Squat', 'machine'],
    ['Leg Press', 'machine'],
    ['Single-Leg Press', 'machine'],
    ['Leg Extension (Machine)', 'machine'],
    ['Single-Leg Extension', 'machine'],
    ['Goblet Squat', 'kettlebell'],
    ['Bulgarian Split Squat (Dumbbell)', 'dumbbell'],
    ['Bulgarian Split Squat (Barbell)', 'barbell'],
    ['Split Squat (Dumbbell)', 'dumbbell'],
    ['Walking Lunge (Dumbbell)', 'dumbbell'],
    ['Reverse Lunge (Dumbbell)', 'dumbbell'],
    ['Forward Lunge (Barbell)', 'barbell'],
    ['Step Up (Dumbbell)', 'dumbbell'],
    ['Sissy Squat', 'bodyweight', 'reps'],
    ['Belt Squat', 'machine'],
    ['Zercher Squat', 'barbell'],
    ['Wall Sit', 'bodyweight', 'duration'],
    ['Air Squat', 'bodyweight', 'reps'],
    ['Cyclist Squat', 'barbell'],
  ],
  hamstrings: [
    ['Romanian Deadlift (Barbell)', 'barbell'],
    ['Romanian Deadlift (Dumbbell)', 'dumbbell'],
    ['Stiff-Leg Deadlift', 'barbell'],
    ['Single-Leg Romanian Deadlift', 'dumbbell'],
    ['Leg Curl (Machine)', 'machine'],
    ['Seated Leg Curl', 'machine'],
    ['Lying Leg Curl', 'machine'],
    ['Standing Leg Curl', 'machine'],
    ['Nordic Curl', 'bodyweight', 'reps'],
    ['Glute-Ham Raise', 'bodyweight', 'reps'],
    ['Good Morning (Safety Bar)', 'barbell'],
    ['Cable Pull-Through', 'cable'],
    ['Kettlebell Swing', 'kettlebell', 'reps'],
    ['Slider Leg Curl', 'bodyweight', 'reps'],
  ],
  glutes: [
    ['Hip Thrust (Barbell)', 'barbell'],
    ['Hip Thrust (Machine)', 'machine'],
    ['Single-Leg Hip Thrust', 'bodyweight', 'reps'],
    ['Glute Bridge', 'bodyweight', 'reps'],
    ['Glute Bridge (Barbell)', 'barbell'],
    ['Cable Kickback', 'cable'],
    ['Glute Kickback (Machine)', 'machine'],
    ['Back Extension (Glute-Focused)', 'bodyweight', 'reps'],
    ['Sumo Squat (Dumbbell)', 'dumbbell'],
    ['Curtsy Lunge', 'dumbbell'],
    ['Frog Pump', 'bodyweight', 'reps'],
    ['Banded Glute Bridge', 'band', 'reps'],
    ['Step Up (High Box)', 'dumbbell'],
  ],
  abductors: [
    ['Hip Abduction (Machine)', 'machine'],
    ['Seated Hip Abduction', 'machine'],
    ['Standing Hip Abduction (Cable)', 'cable'],
    ['Banded Lateral Walk', 'band', 'reps'],
    ['Clamshell', 'band', 'reps'],
    ['Side-Lying Leg Raise', 'bodyweight', 'reps'],
    ['Fire Hydrant', 'bodyweight', 'reps'],
    ['Copenhagen Plank (Abduction)', 'bodyweight', 'duration'],
  ],
  adductors: [
    ['Hip Adduction (Machine)', 'machine'],
    ['Seated Hip Adduction', 'machine'],
    ['Standing Hip Adduction (Cable)', 'cable'],
    ['Copenhagen Plank', 'bodyweight', 'duration'],
    ['Sumo Deadlift (Wide Stance)', 'barbell'],
    ['Cossack Squat', 'bodyweight', 'reps'],
    ['Adductor Machine (Plate-Loaded)', 'machine'],
  ],
  calves: [
    ['Calf Raise (Machine)', 'machine'],
    ['Standing Calf Raise', 'machine'],
    ['Seated Calf Raise', 'machine'],
    ['Calf Raise (Smith Machine)', 'smith'],
    ['Calf Raise (Dumbbell)', 'dumbbell'],
    ['Single-Leg Calf Raise', 'bodyweight', 'reps'],
    ['Leg Press Calf Raise', 'machine'],
    ['Donkey Calf Raise', 'machine'],
  ],
  tibialis: [
    ['Tibialis Raise', 'bodyweight', 'reps'],
    ['Tibialis Raise (Weighted)', 'plate'],
    ['Toe Raise (Band)', 'band', 'reps'],
  ],
  hip_flexors: [
    ['Standing Knee Raise (Cable)', 'cable'],
    ['Hanging Knee Raise', 'bodyweight', 'reps'],
    ['Psoas March (Band)', 'band', 'reps'],
    ['Seated Leg Raise', 'bodyweight', 'reps'],
  ],

  // ── Core ─────────────────────────────────────────────────────────────────
  abs: [
    ['Plank', 'bodyweight', 'duration'],
    ['Weighted Plank', 'plate', 'duration'],
    ['Crunch', 'bodyweight', 'reps'],
    ['Cable Crunch', 'cable'],
    ['Sit Up', 'bodyweight', 'reps'],
    ['Decline Sit Up', 'bodyweight', 'reps'],
    ['Ab Wheel Rollout', 'other', 'reps'],
    ['Machine Crunch', 'machine'],
    ['V-Up', 'bodyweight', 'reps'],
    ['Dead Bug', 'bodyweight', 'reps'],
    ['Hollow Body Hold', 'bodyweight', 'duration'],
    ['Toes to Bar', 'bodyweight', 'reps'],
    ['Stability Ball Crunch', 'other', 'reps'],
  ],
  lower_abs: [
    ['Hanging Leg Raise', 'bodyweight', 'reps'],
    ['Captain’s Chair Leg Raise', 'bodyweight', 'reps'],
    ['Lying Leg Raise', 'bodyweight', 'reps'],
    ['Reverse Crunch', 'bodyweight', 'reps'],
    ['Flutter Kick', 'bodyweight', 'duration'],
    ['Mountain Climber', 'bodyweight', 'duration'],
  ],
  obliques: [
    ['Russian Twist', 'medicine_ball', 'reps'],
    ['Cable Woodchop', 'cable'],
    ['Pallof Press', 'cable'],
    ['Side Plank', 'bodyweight', 'duration'],
    ['Side Bend (Dumbbell)', 'dumbbell'],
    ['Bicycle Crunch', 'bodyweight', 'reps'],
    ['Landmine Twist', 'barbell'],
    ['Suitcase Carry', 'dumbbell', 'duration'],
  ],

  // ── Neck, full body, conditioning ────────────────────────────────────────
  neck: [
    ['Neck Curl', 'plate', 'reps'],
    ['Neck Extension', 'plate', 'reps'],
    ['Neck Harness Extension', 'other'],
  ],
  full_body: [
    ['Clean and Jerk', 'barbell'],
    ['Power Clean', 'barbell'],
    ['Hang Clean', 'barbell'],
    ['Snatch', 'barbell'],
    ['Power Snatch', 'barbell'],
    ['Thruster', 'barbell'],
    ['Burpee', 'bodyweight', 'reps'],
    ['Turkish Get-Up', 'kettlebell'],
    ['Man Maker', 'dumbbell', 'reps'],
    ['Sled Push', 'sled', 'distance'],
    ['Sled Drag', 'sled', 'distance'],
    ['Battle Ropes', 'other', 'duration'],
    ['Devil Press', 'dumbbell', 'reps'],
    ['Wall Ball', 'medicine_ball', 'reps'],
  ],
  cardio: [
    ['Run', 'other', 'distance'],
    ['Treadmill Run', 'cardio_machine', 'distance'],
    ['Incline Walk', 'cardio_machine', 'duration'],
    ['Walk', 'other', 'distance'],
    ['Cycling', 'other', 'distance'],
    ['Stationary Bike', 'cardio_machine', 'distance'],
    ['Assault Bike', 'cardio_machine', 'duration'],
    ['Row (Machine)', 'cardio_machine', 'distance'],
    ['Ski Erg', 'cardio_machine', 'distance'],
    ['Stair Climber', 'cardio_machine', 'duration'],
    ['Elliptical', 'cardio_machine', 'duration'],
    ['Swim', 'other', 'distance'],
    ['Jump Rope', 'other', 'duration'],
    ['Hike', 'other', 'distance'],
    ['Sprint Intervals', 'other', 'duration'],
    ['Stretching', 'bodyweight', 'duration'],
    ['Yoga', 'bodyweight', 'duration'],
    ['Mobility Work', 'bodyweight', 'duration'],
  ],
};

/** Flattened, with the coarse group derived so it can never disagree. */
export const EXERCISE_CATALOG: CatalogEntry[] = Object.entries(BY_TARGET).flatMap(
  ([target, rows]) =>
    (rows ?? []).map(([name, equipment, kind]) => ({
      name,
      muscle: GROUP_OF[target as MuscleTarget],
      target: target as MuscleTarget,
      equipment,
      kind: kind ?? ('weight_reps' as ExerciseKind),
    })),
);
